import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Header from "@/components/Header/Header"
import { auth } from "./api/auth/[nextauth]/route"
import { SessionProvider } from 'next-auth/react'
import { ChatProvider } from "@/contexts/ChatContext/ChatContext"
import { Toaster } from "@/components/ui/sonner"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode
  params: {locale: string}
}>) {
  const session = await auth()
  
  return (
    <html lang={params.locale}>
      <body className={`${inter.className} standard min-h-screen`}>
        <SessionProvider session={session} key={session?.user?.id || null}>
          <ChatProvider>
            {session?.user && <Header/>}
            {children}
            <Toaster/>
          </ChatProvider>
        </SessionProvider>
      </body>
    </html>
  )
}
