import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode
  params: {locale: string}
}>) {

  
  return (
    <html lang={params.locale}>
      <body className={`${inter.className} standard min-h-screen`}>
          {children}
      </body>
    </html>
  )
}
